name: Build and Deploy 🚀

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  prettier:
    name: 🧪 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci

      - name: 🔍 Format
        run: npm run format

  eslint:
    name: ✅ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci

      - name: 🪄 Lint
        run: npm run lint

  build:
    name: ⚙️ Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Download deps
        run: npm ci

      - name: ⚒️ Build
        run: npm run build

      - name: ✈️ Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist
